# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2023-12-21 10:07:09
"""
import arcpy
from arcpy.sa import *

def RasterTilesToMosaic():  # RasterTilesToMosaic

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")

    T11TPN_20230702T182921_TCI_10m_jp2 = arcpy.Raster("Prefire_rasters\\T11TPN_20230702T182921_TCI_10m.jp2")
    T11TQN_20230702T182921_TCI_10m_jp2 = arcpy.Raster("Prefire_rasters\\T11TQN_20230702T182921_TCI_10m.jp2")
    T11UPP_20230702T182921_TCI_10m_jp2 = arcpy.Raster("Prefire_rasters\\T11UPP_20230702T182921_TCI_10m.jp2")
    T11UQP_20230702T182921_TCI_10m_jp2 = arcpy.Raster("Prefire_rasters\\T11UQP_20230702T182921_TCI_10m.jp2")
    Flathead_Indices_gdb = "C:\\Users\\Zach\\Documents\\ArcGIS\\Projects\\Flathead Indices\\Flathead Indices.gdb"
    Flathead_Reservation = "Flathead_Reservation"

    # Process: Mosaic To New Raster (Mosaic To New Raster) (management)
    prefire_mosaic = arcpy.management.MosaicToNewRaster(input_rasters=[T11TPN_20230702T182921_TCI_10m_jp2, T11TQN_20230702T182921_TCI_10m_jp2, T11UPP_20230702T182921_TCI_10m_jp2, T11UQP_20230702T182921_TCI_10m_jp2], output_location=Flathead_Indices_gdb, raster_dataset_name_with_extension="prefire_mosaic", coordinate_system_for_the_raster="PROJCS[\"WGS_1984_UTM_Zone_11N\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-117.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]", number_of_bands=3)[0]
    prefire_mosaic = arcpy.Raster(prefire_mosaic)

    # Process: Extract by Mask (Extract by Mask) (sa)
    Flathead_prefire_mosaic = "C:\\Users\\Zach\\Documents\\ArcGIS\\Projects\\Flathead Indices\\Flathead Indices.gdb\\Flathead_prefire_mosaic"
    Extract_by_Mask = Flathead_prefire_mosaic
    with arcpy.EnvManager(mask=Flathead_Reservation, outputCoordinateSystem="PROJCS[\"WGS_1984_Web_Mercator_Auxiliary_Sphere\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Mercator_Auxiliary_Sphere\"],PARAMETER[\"False_Easting\",0.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",0.0],PARAMETER[\"Standard_Parallel_1\",0.0],PARAMETER[\"Auxiliary_Sphere_Type\",0.0],UNIT[\"Meter\",1.0]]"):
        Flathead_prefire_mosaic = arcpy.sa.ExtractByMask(prefire_mosaic, Flathead_Reservation, "INSIDE", "-12785204.5969 5942706.1043 -12653172.6677 6088110.57 PROJCS[\"WGS_1984_Web_Mercator_Auxiliary_Sphere\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Mercator_Auxiliary_Sphere\"],PARAMETER[\"False_Easting\",0.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",0.0],PARAMETER[\"Standard_Parallel_1\",0.0],PARAMETER[\"Auxiliary_Sphere_Type\",0.0],UNIT[\"Meter\",1.0]]")
        Flathead_prefire_mosaic.save(Extract_by_Mask)


if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="C:\\Users\\Zach\\Documents\\ArcGIS\\Projects\\Flathead Indices\\Flathead Indices.gdb", workspace="C:\\Users\\Zach\\Documents\\ArcGIS\\Projects\\Flathead Indices\\Flathead Indices.gdb"):
        RasterTilesToMosaic()
